PES-866 Enable change of pick-up point in Packeta order detail via widget
Zasilkovna/opencart3 pull request #61
Opened 2022-06-29 21:07 UTC by Mrakor

2022-07-25 09:42 UTC, packeta requested changes

2022-07-25 09:42 UTC, packeta-user commented on upload/system/library/Packetery/Db/BaseRepository.php
> +	public function generateSQLFromData($data)
array jako typ parametru můžeš používat už v PHP 5.6.

2022-07-25 09:42 UTC, packeta-user commented on upload/system/library/Packetery/Order/OrderRepository.php
> +	public function updateById($orderId, $rawData)
array jako typ parametru můžeš používat už v PHP 5.6.

2022-07-25 09:42 UTC, packeta-user commented on upload/system/library/Packetery/Order/OrderRepository.php
> +	 * @return array
Opravdu je návratová hodnota array ?

2022-07-25 09:42 UTC, packeta commented on upload/system/library/Packetery/Tools/Tools.php
> +	public static function issetAll($array, $keys)
Kde se tato funkce používá ?

2022-07-25 09:42 UTC, packeta commented on upload/catalog/model/extension/shipping/zasilkovna.php
> +use Packetery\Tools\Tools;
K čemu je to potřeba ?

2022-07-25 09:42 UTC, packeta commented on upload/catalog/model/extension/shipping/zasilkovna.php
> +		$tools = $this->Tools;
Co přidat `/** @var Tools $tools */`, aby IDE dokázalo napovídat, když načítáme třídu Tools s trochou magie ?

2022-07-26 07:14 UTC, packeta requested changes

2022-07-26 07:14 UTC, packeta-user commented on upload/system/library/Packetery/Page/OrderDetailPage.php
> +	private function isFormValid($postData)
array jako typ parametru můžeš používat už v PHP 5.6.

2022-07-26 07:14 UTC, packeta-user commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +		$routeToListLink = $this->createAdminLink(self::ROUTE_PACKETA_ORDERS);
Proč toto není až těsně před řádkem 988 ($this->response->redirect($routeToListLink);), kde se to na jednom místě používá ? Nebylo by hezčí a přehlednější to mít u sebe ?

2022-07-26 07:14 UTC, packeta-user commented on upload/admin/language/cs-cz/extension/shipping/zasilkovna.php
> +$_['order_detail_changes_saved'] = 'Změny byly uloženy.';
Textaci, že změny byly/nebyly uloženy bych dal k sobě.  Je to přehlednější.

2022-07-26 07:14 UTC, packeta-user commented on upload/admin/view/template/extension/shipping/zasilkovna_order_detail.twig
> +        {% if success %}
Je nutné mít 2 stejné bloky pro výpis nějaké message ? Tyto blogy se liší pouze v použité css třídě alert-*, která může mít hodnoty success nebo danger. Není to zbytečné opakování kódu.  Každý div je ještě navíc jinak naformátován.

2022-07-26 07:14 UTC, packeta-user commented on upload/admin/view/template/extension/shipping/zasilkovna_order_detail.twig
> +                                                      data-branch_name="{{ order.branch_name }}"
Proč předáváš data attributy branch_id a branch_name ? Nemohu najít jejich použití.

2022-07-26 07:14 UTC, packeta-user commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +			'branch_id' => $order['branch_id'],
Kde toto používáš v šabloně ?  Použití widget.branch_id jsem nikde nenašel.

2022-07-26 07:14 UTC, packeta commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +			'api_key' => $settings['shipping_zasilkovna_api_key'],
Co když nebude klíč shipping_zasilkovna_api_key v settings existovat ? Nešlo by použít this->config->get('shipping_zasilkovna_api_key'), když potřebuješ jen jednu hodnotu z celého configu ?

2022-07-26 12:30 UTC, Mrakor commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +		$routeToListLink = $this->createAdminLink(self::ROUTE_PACKETA_ORDERS);
Pouziva se to jeste na radce 992.

2022-07-26 12:33 UTC, Mrakor commented on upload/admin/view/template/extension/shipping/zasilkovna_order_detail.twig
> +        {% if success %}
ne, lisi se to jeste v class te font awsome icony, prepracoval jsem to, aby se div neopakoval.

2022-08-08 06:33 UTC, merged