PES-1031 Extend order list
Zasilkovna/opencart3 pull request #65
Opened 2022-10-19 07:23 UTC by Mrakor

Add column Payment method, enable ordering and filtering by it
Add value to COD column, enable ordering by it
Fixed some typos and few code improvements

2022-11-23 09:14 UTC, packeta requested changes

2022-11-23 09:14 UTC, packeta-user commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +				'cod' => $order['cod'] > 0 ? $this->currency->format($order['cod'], $order['currency_code'], $order['currency_value']) : 0,
Je tato podmínka vůbec nutná ? Nestačilo by jen  'cod' => `$this->currency->format($order['cod'], $order['currency_code'], $order['currency_value'`) ? A v šabloně vyřešit zobrazení ?

2022-11-23 09:14 UTC, packeta-user commented on upload/admin/model/extension/shipping/zasilkovna_orders.php
> +			if (!empty($orderStatuses)) {
Nešlo by to jednoduše:  `$orderStatusesString = implode(',', $orderStatuses)` ?

2022-11-23 09:14 UTC, packeta commented on upload/admin/model/extension/shipping/zasilkovna_orders.php
> +		// add sorting and paging parts (variables with column name and direction is already sanitized in getUrlParameters())
Jaký je význam tohoto komentáře ?

2022-11-24 08:05 UTC, Mrakor commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +				'cod' => $order['cod'] > 0 ? $this->currency->format($order['cod'], $order['currency_code'], $order['currency_value']) : 0,
Naformatovana nulova cod v sablone muze mit tvar 0,00 Kc , $0.00, 0.00€ a podminka v sablone pro zobrazeni prazdneho mista by byla dost divoka.

2022-11-24 08:05 UTC, Mrakor commented on upload/admin/model/extension/shipping/zasilkovna_orders.php
> +		// add sorting and paging parts (variables with column name and direction is already sanitized in getUrlParameters())
ja ho tam nepridaval, uz tam byl,  jen je posunuty, aby bylo cele SQL hezky naformatovane v jednom retezci a v IDE to cele nesvitilo jako vanocni stromecek.

2022-11-24 09:25 UTC, packeta commented on upload/admin/model/extension/shipping/zasilkovna_orders.php
> +		// add sorting and paging parts (variables with column name and direction is already sanitized in getUrlParameters())
pokud je to tedy složitější otázka, založím na její řešení ticket.

2022-11-25 06:40 UTC, packeta commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +				'cod' => $order['cod'] > 0 ? $this->currency->format($order['cod'], $order['currency_code'], $order['currency_value']) : 0,
Bylo by možné, aby podmínka vracela místo 0 prázdný string, jako je to u sloupce exported ?

2022-11-28 10:41 UTC, merged