PES-1394 Page Add vendor
Zasilkovna/opencart3 pull request #79
Opened 2023-05-18 09:08 UTC by Mrakor

2023-05-22 10:32 UTC, packeta requested changes

2023-05-22 10:32 UTC, packeta commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +		$data = $this->initPageData(self::ACTION_ADD_VENDOR, 'Nový vendor');
Nemá být text "Nový vendor" v překladech ? Použij ale "Nový dopravce" .  Vendor je zatím pouze naše interní označení.

2023-05-22 10:32 UTC, packeta commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +		$data['weight_rules'] = $this->getVendorWeightRules($vendorId);
Proč načítáš weight_rules ? pro založení nového vendora to nepotřebuješ.  Jak jsme se dohodli, v rámci tohoto PR neřešíme editaci, jen založení nového vendora.

2023-05-22 10:32 UTC, packeta commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +	{   //mock data
Sem dej TODO, že je potřeba dodělat načítání dopravců z DB, jak jsme se dohodli.

2023-05-22 10:32 UTC, packeta commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +	private function getVendorWeightRules($vendorId) {
Pro založení vendora tuto metodu nepotřebuješ.  Zatím ji tedy odstraň.

2023-05-22 10:32 UTC, packeta commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +	const INTERNAL_VENDORS = [
Chybí překlady.  To pole bych sestavil  takto 'id'=> 'zpoint', 'name'=> 'Výdejní místa',  countries=> ['cz', 'sk', 'ro', 'hu].  Bude to přehlednější a nemusíš několikrát opakovat názvy a idčka

2023-05-22 10:32 UTC, packeta commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +	const INTERNAL_VENDORS = [
místo internal_vendors bych zvolil spíš název "packeta_vendors".

2023-05-22 10:32 UTC, packeta commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +				IF(ISNULL(`zv`.`carrier_id`), 1, `zc`.`is_pickup_points`) AS 'has_pickup_points'
Nejsem si 100% jistý, ale nebyla tato změna v jiném PR ?

2023-05-22 10:32 UTC, packeta commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +	private function updateVendor(array $vendor) {
jak jsme se dohodli,  aktualizaci vendora v rámci ticketu neřešíme.  toto tedy nyní nepotřebujeme.

2023-05-22 10:32 UTC, packeta commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +	public function deleteVendorPricesByIds(array $vendorPriceIds) {
odstranění vendora také teď neřešíme.

2023-05-22 13:17 UTC, packeta requested changes

2023-05-22 13:17 UTC, packeta-user commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +	private function getVendorWeightRules($vendorId) {
tento komentář jsi uzavřel bez vyřešení.

2023-05-22 13:17 UTC, packeta commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +	 * @param bool   $onlyEnabled
není tam nějak moc mezer ?

2023-05-30 13:24 UTC, packeta requested changes

2023-05-30 13:24 UTC, packeta-user commented on upload/admin/language/cs-cz/extension/shipping/zasilkovna.php
> +$_['vendor_add_help_cart_name'] = 'Tooltip pro nazev dopravce v kosiku'; //TODO
TODO musí vždy nějaký popis, aby bylo jasné, co je potřeba dodělat.  Pokud nevíš jakou textaci použít , je nutné to konzultovat během vývoje a ne to předat na CR a čekat, až si toho někdo všimne a řekne ti, co tam má být.  Textace v tomto případě bude:  Název dopravce, který bude uveden v pokladně.

2023-05-30 13:24 UTC, packeta-user commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +	 * @throws ReflectionException
chybí @return void

2023-05-30 13:24 UTC, packeta-user commented on upload/admin/view/template/extension/shipping/zasilkovna_add_vendor.twig
> +    function add() {
Co když bude funkce se stejným názvem deklarována i jiným pluginem třetí strany a bude také načítána v administraci.  Neudělá to problém ?

2023-05-30 13:24 UTC, packeta-user commented on upload/admin/view/template/extension/shipping/zasilkovna_add_vendor.twig
> +    var weight_rule_row = {{ weight_rules|length }};
Pokud je proměnná deklarovaná v obecném prostoru,  neměli bychom ji prefixovat, aby nedošlo k případné kolizi názvů s jiným modulem ?

2023-05-30 13:24 UTC, packeta-user commented on upload/system/library/Packetery/Carrier/CarrierRepository.php
> +	public function getCarriersByCountry($countryCode)
Chybí DOC !!!!

2023-05-30 13:24 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +	private function getAddVendorFormDataFromSession() {
Chybí DOC !!!!

2023-05-30 13:24 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +			($vendor['max_weight'] === null) ? 'NULL' : $vendor['max_weight'],
Klíč  "max_weight" v poli $vendor neexistuje.  Zde plugin vypíše chybu: Notice: Undefined index: max_weight in ....

2023-05-30 13:24 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +			(`carrier_id`, `carrier_name_cart`,`country`, `group`, `free_shipping_limit`, `max_weight`, `is_enabled`)
Sloupec max_weight není součástí tabulky zasilkovna_vendor. Toto způsobí, že při pokusu o uložení modul spadne na chybě "Fatal error: Uncaught Exception: Error: Unknown column 'max_weight' ".

2023-05-30 13:24 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +			foreach ($requiredFields as $requiredField) {
Nevidím smysl iterovat pole o jednom prvku.  Foreach je v tomto případně zbytečný.  Stačí jen podmínka 
if (empty($formData['vendor'])) { ....

2023-05-30 13:24 UTC, packeta-user commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +		if (!empty($postedData) && $postedData['action'] === self::ACTION_ADD_VENDOR) {
Pro zjistění zda byl formulář odeslaný a má se zpracovat používáme v celém pluginu podmínku:
if ($this->request->server['REQUEST_METHOD'] === 'POST') {
Nemá cenu vymýšlet něco jiného na jednom konkrétním místě.   Udělal bych to zde stejně.

2023-05-30 13:24 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +		if ($formData['action'] === ControllerExtensionShippingZasilkovna ::ACTION_ADD_VENDOR) {
Tady bych nejdřív vyřešil if ($formData['action'] !== ControllerExtensionShippingZasilkovna ::ACTION_ADD_VENDOR) ...  
Zbytek logiky pak nebudeš mít zanořený v if {} a kód bude přehlednější.

2023-05-30 13:24 UTC, packeta-user commented on upload/admin/language/cs-cz/extension/shipping/zasilkovna.php
> +$_['vendor_add_entry_cart_name'] = 'Název dopravce v košíku';
Název dopravce v pokladně.

2023-05-30 13:24 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +		if ($formData['action'] === ControllerExtensionShippingZasilkovna ::ACTION_ADD_VENDOR) {
Zde: "ControllerExtensionShippingZasilkovna ::ACTION_ADD_VENDOR" máš chybně napsanou konstantu - před :: máš tam mezeru! PhPStorm takové chyby červeně podtrhává a říká, že konstanta neexistuje (Constant 'ACTION_ADD_VENDOR' not found in \ControllerExtensionShippingZasilkovna).

2023-05-30 13:24 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +				'vendor_id' => ($vendor['id'] === 'zpoint') ? '' : $vendor['id'],
Zde připravuješ pole ze kterého pak v šabloně sestavuješ select pro výběr dopravců.  Nemůžeš mít vendor_id prázdný string.  Prázdný string už používáš v selectu v promptu.  Pokud pak zvolíš dopravce "Packeta výdejní místo" neprojde dopravce validací a dopravce nejde uložit, protože ve validaci kontroluješ :
if (empty($formData[$requiredField]))

2023-05-30 13:24 UTC, packeta commented on upload/admin/view/template/extension/shipping/zasilkovna_add_vendor.twig
> +                                                {% if vendor.vendor_id == vendor %}
Tato podmínka nebude nikdy splněna. Nemůžeš porovnávat vendor (array) s vendor.vendor_id (prvek pole). výsledek bude vždy false.

2023-05-30 13:24 UTC, packeta commented on upload/admin/view/template/extension/shipping/zasilkovna_add_vendor.twig
> +                                                {% if vendor.vendor_id == vendor %}
v poli vendor nemáš prvek "vendor_id", ale "id".  Ve value jednotlivých option tak nebudeš mít žádnou hodnotu. Formulář po odeslání nemůže projít validací a bude hlásit, že dopravce nebyl vybrán.

2023-06-01 16:36 UTC, packeta requested changes

2023-06-01 16:36 UTC, packeta-user commented on upload/admin/view/template/extension/shipping/zasilkovna_add_vendor.twig
> +    function addWeightRuleRow() {
Co když bude funkce se stejným názvem deklarována i jiným pluginem třetí strany a bude také načítána v globálním prostoru, jako ji máš ty ? Neudělá to problém ?

2023-06-01 16:36 UTC, packeta-user commented on upload/admin/controller/extension/shipping/zasilkovna.php
> +		if (($this->request->server['REQUEST_METHOD'] === 'POST') && ($postedData['action'] === self::ACTION_ADD_VENDOR)) {
toto je v podmínce zbytečné: && ($postedData['action'] === self::ACTION_ADD_VENDOR)

2023-06-01 16:36 UTC, packeta-user commented on upload/system/library/Packetery/Carrier/CarrierRepository.php
> +	public function getCarriersByCountry($countryCode)
U této metody uvádíš, že může vrátit mixed.  Výsledek této metody ale předáváš jako první parametr array_filter(), což musí být array.  Buď máš špatně návratový typ, nebo nemáš ošetřeno, abys nepředal array_filter chybný parametr.

2023-06-01 16:36 UTC, packeta commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +	public function getTranslations() {
Proč potřebuješ sestavit pole s překlady a předávat je šabloně ?  Twig si natahuje překlady automaticky.  V šabloně by ti mělo stačit zavolat např.  {{vendor_add_vendor_label}} a dostaneš překlad ze slovníku.

2023-06-01 17:42 UTC, packeta requested changes

2023-06-01 17:42 UTC, packeta commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +			if (empty($formData['vendor'])) {
Pokud ve formuláři nevyberu žádného dopravce, tak $formData['vendor'] bude "-1".  Takže to projde touto podmínkou a vytvoří se vendor , kde carrier_id je -1.

2023-06-01 17:42 UTC, packeta commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +			if (in_array($key, ['vendor', 'country', 'vendor_group', 'cart_name', 'free_shipping_limit', 'is_enabled', 'weight_rules'])) {
Toto není dobrý způsob řešení.  Musíš dávat pozor, aby jsi v tomto poli neměl stejný klíč jako v poli $data v metodě add_vendor(), protože tam děláš array_merge($data, $prefilledData).   Druhým důvodem je to, že když v budoucnu rozšíříš formulář o další pole, tak si budeš muset pamatovat,  že musíš jít do této metody a zde upravit obsah pole.  To je velice náchylné na chyby.

2023-06-01 17:42 UTC, packeta commented on upload/admin/view/template/extension/shipping/zasilkovna_add_vendor.twig
> +                                        <option value="-1">{{ text_select_vendor }}</option>
Pokud není v selectu vybraná hodnota, nastav value na prázdný string a ošetři v PHP.  Použít hodnot "-1" je velice nešťastné a vede to k chybám.

2023-06-08 10:29 UTC, xpavp03 requested changes

2023-06-08 10:29 UTC, xpavp03 commented on upload/admin/controller/extension/shipping/zasilkovna.php
>  				$data['form']['weight_rules'] = $vendorAddEditPage->removeEmptyWeightRules($data['form']['weight_rules']);
Proč tady voláš removeEmptyWeightRules() ještě jednou?

2023-06-08 10:29 UTC, xpavp03 commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +			if (!is_numeric($rule['price']) || $rule['price'] <= 0) {
nechceme povolit cenu 0?
váhu 0 ne, to chápu, ale třeba chce dopravu zadarmo pro váhu do nějakého limitu... Zeptej se Jardy, prosím.

2023-06-19 07:31 UTC, packeta requested changes

2023-06-19 07:31 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +	public function validateForm(array $postedData) {
přejmenuj na validate()

2023-06-19 07:31 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +				$errors[] = $this->language->get($error);
Proč překládáš už jednou přeložený řetězec ?

2023-06-19 07:31 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +		if ($formData['weight_rules'] && is_array($formData['weight_rules'])) {
V jakém případě bude tato podmínka vyhodnocena jako false ? Toto by mělo být ošetřeno už při validaci.  Pokud by byla podmínka vyhodnocena jako false,  bude vendor v DB nekompletní (bude existovat záznam v tabulce vendor, ale nebude existovat záznam v tabulce vendor_price).

2023-06-19 07:31 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +			if ($vendorPrices) {
Ta samá otázka jako v předchozím komentáři .  O validaci vendora by se měla starat validace.  Při ukládání je další validace zbytečná.

2023-06-19 07:31 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +	public function getCarriersByCountry($countryCode) {
Co dělá tato metoda ? Podle názvu bych čekal, že jako výsledek dostanu všechny dopravce konkrétní země.

2023-06-19 07:31 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +	public function getInternalVendorsByCountry($countryCode) {
Proč je tato metoda v repositáři ?

2023-06-19 07:31 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +			if (!is_numeric($rule['price']) || $rule['price'] <= 0) {
Eshopy chtějí dopravu zdarma od určité částky.  Dopravu zdarma podle hmotnosti jsem nikdy neviděl.  V původním nastavení modulu to také nejde nastavit a žádný eshop nám nikdy nepsal, že by něco takového chtěl.  Takže bych to nechal jak toje.

2023-06-19 07:31 UTC, packeta commented on upload/system/library/Packetery/Vendor/AddEditPage.php
> +class AddEditPage {
Přejmenoval bych to na "Page".

2023-06-19 07:31 UTC, packeta commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +		return null;
V jakém případě může nastat tato situace a metoda vrací null ?

2023-06-19 07:57 UTC, packeta requested changes

2023-06-19 07:57 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +		if ($queryResult->num_rows === 0) {
Proč je zde tato podmínka ?

2023-06-19 07:57 UTC, packeta-user commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +		foreach($queryResult->rows as $row) {
Není to foreach zbytečné ? Nestačilo by return array_column($queryResult->rows, 'group')

2023-06-19 08:00 UTC, packeta requested changes

2023-06-19 08:00 UTC, packeta commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +		['id' => 'zpoint', 'name' => 'vendor_add_zpoint', 'countries' => ['cz', 'sk', 'hu', 'ro']],
Za posledním prvkem pole píšeme vždy ","

2023-06-20 10:07 UTC, Mrakor commented on upload/system/library/Packetery/Vendor/VendorRepository.php
> +	public function getInternalVendorsByCountry($countryCode) {
za me sem patri.  repozitar chapu jako centralni misto pro praci s nejakym typem entity.

2023-06-27 08:39 UTC, merged